---
- name: Create dhcp config for host
  template: src=node_dhcp.conf.j2 dest="/etc/dhcp/dhcpd.d/{{ inventory_hostname_short }}.conf"
  when: use_dhcp or use_pxe

- name: Create pxe boot data (read by boot.py)
  template: src=node_pxe.conf.j2 dest="/var/www/provision/nodes/{{ inventory_hostname_short }}.conf"
  when: use_pxe

- name: Create kickstart file
  template: src=kickstart.j2 dest="/var/www/html/bootstrap/{{ inventory_hostname_short }}.ks"
  when: use_pxe and use_kickstart

- name: Create autoyast file
  template: src=autoyast.j2 dest="/var/www/html/bootstrap/{{ inventory_hostname_short }}.xml"
  when: use_pxe and use_autoyast
  
- name: Find all the configs in dhcpd.d directory
  run_once: true
  find:
    paths: "/etc/dhcp/dhcpd.d/"
    patterns: "*.conf"
  register: configs
 
- name: Clear hosts config
  run_once: true
  shell: "echo '# Ansible ansible-role-dhcp-kickstart managed' > /etc/dhcp/dhcpd_hosts.conf"

- name: Update main dhcpd include file to include all hosts
  run_once: true
  shell: "echo 'include \"{{ item.path }}\";' >> /etc/dhcp/dhcpd_hosts.conf"
  with_items: "{{ configs.files }}"
  no_log: true # suppress item printout to console
  notify: restart dhcpd

- meta: flush_handlers

- name: Generate hosts file from inventory
  run_once: true
  template: src=hosts.j2 dest="{{ dhcp_hosts_file }}" owner=root group=root mode=0644
  when: generate_hosts_file
